/* 管理后台多页入口；顺序与迁移前 admin/index.html 严格一致。 */
import '@/legacy/travel-theme-global'
import '@/legacy/theme-effects-global'
import '@/legacy/travel-api-global'
import '@/legacy/travel-map-global'
import '@/legacy/local-draft-global'
import '@/legacy/journal-media-global'
import '@/legacy/journal-blocks-global'
import '@/legacy/day-route-global'
import '@/admin/register-pages'

import '../../../src/main/resources/static/js/common/journal-block-editor.js'
import '../../../src/main/resources/static/js/admin/shared.js'
import '../../../src/main/resources/static/js/admin/trip-workspace.js'
import '../../../src/main/resources/static/js/admin/journal-editor.js'
import '../../../src/main/resources/static/js/admin/moments.js'
import '../../../src/main/resources/static/js/admin/studio.js'
import '../../../src/main/resources/static/js/admin-app.js'
import '../../../src/main/resources/static/js/common/custom-cursor.js'
import '../../../src/main/resources/static/js/common/pwa.js'
