-- 中等尺寸图片规格，以及草稿预览令牌。

-- ---------------------------------------------------------------- 中等规格
--
-- 原先只有 1280 的 display 和 480 的 thumbnail。手机打开日记时下载的仍然是完整的
-- 1280 文件，白白多花一倍以上流量。补一档 768，配合前端 srcset 让浏览器自己挑。
--
-- 存量图片这一列为空，访问时回落到 display，不需要回填也不会坏。
alter table media_asset add column medium_object_key varchar(512);

comment on column media_asset.medium_object_key is '768px 中等规格对象键；存量图片为空，访问时回落到 display';

-- ---------------------------------------------------------------- 草稿预览
--
-- 公开接口只认 PUBLISHED，所以发布前看不到日记在真实主题和站点外壳下的样子。
-- 这里给草稿发一个带令牌的临时链接：知道链接的人可以预览，但链接会过期，
-- 也可以随时作废，不需要把草稿真的公开出去。
create table journal_preview_token (
    id bigint generated by default as identity primary key,
    journal_entry_id bigint not null references journal_entry(id) on delete cascade,
    token varchar(64) not null unique,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

comment on table journal_preview_token is '草稿预览令牌，用于在不发布的前提下分享日记预览';
comment on column journal_preview_token.token is '随机令牌，出现在预览链接里';
comment on column journal_preview_token.expires_at is '过期时间，过期后链接失效';

create index idx_journal_preview_token_journal on journal_preview_token(journal_entry_id);
