-- 随手记（Moment）。
--
-- 日记是「晚上坐下来写的那篇」，随手记是「路上二十秒记完的那一条」：
--   10:23  浅草看到一只很胖的柴犬。[照片] 📍浅草
-- 两者不是同一个东西，所以不复用 journal_entry——日记有标题、slug、发布状态、
-- 主题这一整套，随手记一个都不需要，硬塞进去只会让两边都别扭。
--
-- 随手记的归宿是被整理成日记。整理之后原始记录仍然保留（journal_entry_id 回填），
-- 这样「那天到底发生了什么」永远还能翻回最初写下的样子。

create table moment (
    id bigint generated by default as identity primary key,
    trip_id bigint not null references trip(id) on delete cascade,
    trip_stop_id bigint references trip_stop(id) on delete set null,
    -- 记的是「那一刻」而不是「写下的时刻」：补记昨天的事很常见，所以允许作者改
    occurred_at timestamptz not null default now(),
    content text not null default '',
    place_name varchar(120),
    latitude numeric(10, 7),
    longitude numeric(10, 7),
    mood varchar(40),
    -- 已经被整理进哪篇日记。为空表示还散着，这也是「今天有几条待整理」的依据
    journal_entry_id bigint references journal_entry(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

comment on table moment is '随手记：旅途中即时记下的一条，可以带照片和地点，之后整理成日记';
comment on column moment.occurred_at is '这件事发生的时刻，不是写下的时刻，允许作者补记';
comment on column moment.content is '正文，通常一两句话';
comment on column moment.place_name is '地点名称，可以来自定位反查，也可以手填';
comment on column moment.latitude is '纬度，来自设备定位或照片 EXIF';
comment on column moment.longitude is '经度，来自设备定位或照片 EXIF';
comment on column moment.mood is '当时的心情，一个词';
comment on column moment.journal_entry_id is '已整理进哪篇日记；为空表示还没整理';

-- 主查询永远是「这次旅行的这一天有哪些」，所以按 trip + 时间倒序建索引
create index idx_moment_trip_time on moment(trip_id, occurred_at desc);
-- 「还有多少条没整理」这个查询会命中它
create index idx_moment_unsorted on moment(trip_id, journal_entry_id) where journal_entry_id is null;

create table moment_media (
    id bigint generated by default as identity primary key,
    moment_id bigint not null references moment(id) on delete cascade,
    media_asset_id bigint not null references media_asset(id),
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (moment_id, media_asset_id)
);

comment on table moment_media is '随手记与照片的关联；整理成日记时照片会被同一份 media_asset 复用，不重新上传';
comment on column moment_media.sort_order is '同一条随手记内的照片顺序，从 0 开始';

create index idx_moment_media_asset on moment_media(media_asset_id);
