create table admin_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    password_hash varchar(255) not null,
    display_name varchar(64) not null,
    enabled boolean not null default true,
    last_login_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table media_asset (
    id bigint generated by default as identity primary key,
    bucket_name varchar(128) not null,
    original_object_key varchar(512) not null unique,
    display_object_key varchar(512) not null unique,
    thumbnail_object_key varchar(512) not null unique,
    original_filename varchar(255) not null,
    content_type varchar(100) not null,
    file_size bigint not null check (file_size > 0),
    width integer,
    height integer,
    checksum_sha256 varchar(64),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table trip (
    id bigint generated by default as identity primary key,
    title varchar(160) not null,
    slug varchar(180) not null unique,
    summary varchar(1000),
    status varchar(32) not null,
    start_date date not null,
    end_date date not null,
    default_currency char(3) not null default 'CNY',
    cover_media_id bigint references media_asset(id) on delete set null,
    internal_note text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_trip_dates check (end_date >= start_date)
);

create table trip_stop (
    id bigint generated by default as identity primary key,
    trip_id bigint not null references trip(id) on delete cascade,
    city_name varchar(120) not null,
    region_name varchar(120),
    country_name varchar(120) not null,
    country_code char(2),
    latitude numeric(9,6) not null,
    longitude numeric(9,6) not null,
    arrival_date date,
    departure_date date,
    sort_order integer not null default 0,
    note varchar(1000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_stop_lat check (latitude between -90 and 90),
    constraint chk_stop_lng check (longitude between -180 and 180),
    constraint chk_stop_dates check (departure_date is null or arrival_date is null or departure_date >= arrival_date)
);

create table itinerary_item (
    id bigint generated by default as identity primary key,
    trip_id bigint not null references trip(id) on delete cascade,
    trip_stop_id bigint references trip_stop(id) on delete set null,
    item_date date not null,
    start_time time,
    end_time time,
    type varchar(32) not null,
    title varchar(200) not null,
    address varchar(500),
    note text,
    planned_cost numeric(14,2),
    completed boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_itinerary_cost check (planned_cost is null or planned_cost >= 0),
    constraint chk_itinerary_time check (end_time is null or start_time is null or end_time >= start_time)
);

create table budget_category (
    id bigint generated by default as identity primary key,
    trip_id bigint not null references trip(id) on delete cascade,
    code varchar(32) not null,
    name varchar(80) not null,
    planned_amount numeric(14,2) not null default 0,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_budget_trip_code unique (trip_id, code),
    constraint chk_budget_amount check (planned_amount >= 0)
);

create table expense (
    id bigint generated by default as identity primary key,
    trip_id bigint not null references trip(id) on delete cascade,
    budget_category_id bigint not null references budget_category(id),
    trip_stop_id bigint references trip_stop(id) on delete set null,
    expense_date date not null,
    amount numeric(14,2) not null,
    description varchar(500) not null,
    merchant varchar(160),
    note text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_expense_amount check (amount > 0)
);

create table journal_entry (
    id bigint generated by default as identity primary key,
    trip_id bigint not null references trip(id) on delete cascade,
    trip_stop_id bigint references trip_stop(id) on delete set null,
    title varchar(200) not null,
    slug varchar(220) not null unique,
    excerpt varchar(500),
    content_markdown text not null default '',
    status varchar(32) not null default 'DRAFT',
    occurred_on date not null,
    cover_media_id bigint references media_asset(id) on delete set null,
    published_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_journal_publish check ((status = 'DRAFT') or (status = 'PUBLISHED' and published_at is not null))
);

create table journal_media (
    id bigint generated by default as identity primary key,
    journal_entry_id bigint not null references journal_entry(id) on delete cascade,
    media_asset_id bigint not null references media_asset(id) on delete restrict,
    caption varchar(500),
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_journal_media unique (journal_entry_id, media_asset_id)
);

create index idx_trip_status_dates on trip(status, start_date desc);
create index idx_trip_stop_trip_sort on trip_stop(trip_id, sort_order);
create index idx_itinerary_trip_date on itinerary_item(trip_id, item_date, sort_order);
create index idx_budget_trip_sort on budget_category(trip_id, sort_order);
create index idx_expense_trip_date on expense(trip_id, expense_date);
create index idx_journal_status_published on journal_entry(status, published_at desc);
create index idx_journal_trip_occurred on journal_entry(trip_id, occurred_on desc);
create index idx_journal_media_entry_sort on journal_media(journal_entry_id, sort_order);
