alter table trip_stop
    add column place_id varchar(128),
    add column formatted_address varchar(500),
    add column adcode varchar(32),
    add column coordinate_system varchar(20) not null default 'GCJ02',
    add column location_source varchar(30) not null default 'MANUAL';

create index idx_trip_stop_place_id on trip_stop(place_id) where place_id is not null;
create index idx_trip_stop_adcode on trip_stop(adcode) where adcode is not null;

create table journal_template (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    description varchar(500),
    category varchar(50) not null default 'CUSTOM',
    definition_json jsonb not null,
    version integer not null default 1,
    enabled boolean not null default true,
    builtin boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_journal_template_version check (version > 0)
);

create index idx_journal_template_enabled on journal_template(enabled, builtin desc, updated_at desc);

alter table journal_entry
    add column template_id bigint references journal_template(id) on delete set null,
    add column template_version integer,
    add column template_data jsonb,
    add column template_snapshot jsonb,
    add column template_detached boolean not null default false;

insert into journal_template(name, description, category, definition_json, builtin) values
('城市一日游', '自动整理当天路线、行程、照片和花费，适合城市漫步。', 'CITY_DAY',
 '{"title":"城市一日游","blocks":[{"id":"basic","type":"trip-info","title":"旅行信息","required":true,"config":{"showWeather":true,"showMood":true}},{"id":"route","type":"route","title":"今日路线","required":false,"config":{"source":"itinerary"}},{"id":"itinerary","type":"itinerary","title":"今日行程","required":false,"config":{"source":"itinerary"}},{"id":"story","type":"textarea","title":"旅途记录","required":true,"config":{"placeholder":"记录今天印象最深的事情"}},{"id":"photos","type":"gallery","title":"今日照片","required":false,"config":{"layout":"grid","imageSize":"medium"}},{"id":"expense","type":"expense-summary","title":"今日花费","required":false,"config":{"source":"expense"}},{"id":"feeling","type":"textarea","title":"今日感受","required":false,"config":{"placeholder":"写下此刻的心情"}}]}'::jsonb, true),
('多日旅行总结', '把整段旅程的路线、花费、照片和经验整理成完整总结。', 'TRIP_SUMMARY',
 '{"title":"多日旅行总结","blocks":[{"id":"basic","type":"trip-info","title":"旅行概览","required":true,"config":{"showWeather":false,"showMood":false}},{"id":"route","type":"route","title":"城市路线","required":false,"config":{"source":"trip"}},{"id":"highlight","type":"textarea","title":"最喜欢的地方","required":true,"config":{"placeholder":"这次旅行最难忘的瞬间"}},{"id":"expense","type":"expense-summary","title":"旅行花费","required":false,"config":{"source":"trip"}},{"id":"photos","type":"gallery","title":"旅途照片","required":false,"config":{"layout":"grid","imageSize":"medium"}},{"id":"lessons","type":"textarea","title":"踩坑与建议","required":false,"config":{"placeholder":"写给下一次旅行的自己"}}]}'::jsonb, true),
('美食探店', '记录餐厅、菜品、评分、环境和是否值得再来。', 'FOOD',
 '{"title":"美食探店","blocks":[{"id":"basic","type":"trip-info","title":"地点与日期","required":true,"config":{"showWeather":false,"showMood":true}},{"id":"restaurant","type":"text","title":"餐厅名称","required":true,"config":{"placeholder":"餐厅或摊位名称"}},{"id":"rating","type":"rating","title":"推荐指数","required":true,"config":{"max":5}},{"id":"dishes","type":"gallery","title":"菜品照片","required":false,"config":{"layout":"grid","imageSize":"medium"}},{"id":"taste","type":"textarea","title":"味道与价格","required":true,"config":{"placeholder":"口味、分量、人均价格"}},{"id":"environment","type":"textarea","title":"环境与服务","required":false,"config":{"placeholder":"用餐环境和服务感受"}},{"id":"recommend","type":"quote","title":"一句话推荐","required":false,"config":{"placeholder":"会不会再来？"}}]}'::jsonb, true),
('景点打卡', '适合记录景点交通、门票、拍照位置和游览建议。', 'ATTRACTION',
 '{"title":"景点打卡","blocks":[{"id":"basic","type":"trip-info","title":"景点信息","required":true,"config":{"showWeather":true,"showMood":false}},{"id":"transport","type":"text","title":"到达方式","required":false,"config":{"placeholder":"交通方式和耗时"}},{"id":"ticket","type":"text","title":"门票与开放时间","required":false,"config":{"placeholder":"门票、预约和开放时间"}},{"id":"rating","type":"rating","title":"推荐指数","required":true,"config":{"max":5}},{"id":"photos","type":"gallery","title":"最佳机位","required":false,"config":{"layout":"grid","imageSize":"large"}},{"id":"tips","type":"textarea","title":"游览建议","required":false,"config":{"placeholder":"路线、避坑和注意事项"}}]}'::jsonb, true),
('图片日记', '以照片和图注为主，让竖图、横图和照片墙保持整齐。', 'PHOTO',
 '{"title":"图片日记","blocks":[{"id":"basic","type":"trip-info","title":"日期与地点","required":true,"config":{"showWeather":true,"showMood":true}},{"id":"intro","type":"text","title":"开场","required":false,"config":{"placeholder":"用一句话开始今天的故事"}},{"id":"hero","type":"image","title":"主照片","required":false,"config":{"imageSize":"large","align":"center"}},{"id":"photos","type":"gallery","title":"照片墙","required":true,"config":{"layout":"grid","imageSize":"medium"}},{"id":"ending","type":"textarea","title":"照片背后的故事","required":false,"config":{"placeholder":"写下镜头之外的感受"}}]}'::jsonb, true),
('旅途随笔', '轻量文字模板，适合在手机上快速记录当下。', 'ESSAY',
 '{"title":"旅途随笔","blocks":[{"id":"basic","type":"trip-info","title":"此刻","required":true,"config":{"showWeather":true,"showMood":true}},{"id":"story","type":"textarea","title":"随笔","required":true,"config":{"placeholder":"不必完整，先写下此刻最想记住的事"}},{"id":"quote","type":"quote","title":"今日一句","required":false,"config":{"placeholder":"一句想留给未来自己的话"}},{"id":"photo","type":"image","title":"此刻的照片","required":false,"config":{"imageSize":"medium","align":"center"}}]}'::jsonb, true);
