create table theme_preset (
    id bigint generated by default as identity primary key,
    theme_key varchar(80) not null unique,
    name varchar(100) not null,
    description varchar(500),
    base_theme_key varchar(64) not null default 'travel-classic',
    preview_image_url varchar(500),
    definition_json jsonb not null default '{}'::jsonb,
    builtin boolean not null default false,
    enabled boolean not null default true,
    version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index idx_theme_preset_enabled on theme_preset(enabled, builtin desc, updated_at desc);

alter table trip add column theme_key varchar(80);
alter table journal_entry add column theme_key varchar(80);

insert into theme_preset
    (theme_key, name, description, base_theme_key, preview_image_url, definition_json, builtin)
values
    ('travel-classic', '远行手记', '暖白纸张、森林绿与陶土色的旅行杂志主题', 'travel-classic',
     '/img/theme-travel-classic-preview.png',
     '{
       "colors":{"background":"#F7F2E8","surface":"#FFFCF6","surfaceSoft":"#F1E7D7","primary":"#264A3D","primarySoft":"#42685A","accent":"#C76D4B","accentHover":"#B65B3B","sand":"#DFC9A8","text":"#2A2D2B","muted":"#77736B","border":"#E6DAC8","danger":"#B7483E"},
       "typography":{"headingFamily":"serif","bodyFamily":"sans","bodySize":16,"lineHeight":1.8},
       "shape":{"cardRadius":12,"imageRadius":8,"buttonRadius":8},
       "layout":{"contentWidth":1200,"articleWidth":760,"density":"comfortable","homeLayout":"editorial"},
       "image":{"style":"natural","shadow":"soft","defaultRatio":"16:9"},
       "motion":{"level":"subtle"}
     }'::jsonb, true),
    ('sanya-breeze', '三亚海风', '海水青、珊瑚橙与日光沙色的热带海岸主题', 'sanya-breeze',
     '/img/home-hero-sanya.png',
     '{
       "colors":{"background":"#F2F7F3","surface":"#FFFDF7","surfaceSoft":"#E4F2EE","primary":"#155D5A","primarySoft":"#327B76","accent":"#E97855","accentHover":"#D86443","sand":"#E7CAA2","text":"#263536","muted":"#6B7D79","border":"#D8E5DE","danger":"#C54F45"},
       "typography":{"headingFamily":"serif","bodyFamily":"sans","bodySize":16,"lineHeight":1.8},
       "shape":{"cardRadius":12,"imageRadius":10,"buttonRadius":10},
       "layout":{"contentWidth":1200,"articleWidth":780,"density":"relaxed","homeLayout":"editorial"},
       "image":{"style":"rounded","shadow":"soft","defaultRatio":"16:9"},
       "motion":{"level":"subtle"}
     }'::jsonb, true)
on conflict (theme_key) do nothing;
