-- 九套内置主题预设。
--
-- 需求要点：一套预设必须同时影响配色、字体、背景、卡片、图片、圆角、阴影、布局和动效，
-- 而不是只换颜色，所以每条记录的 definition_json 都覆盖了全部 token 区块。
-- 可调项清单见 ThemePresetService.SCHEMA，视觉实现见 static/css/theme-tokens.css。
--
-- 全部 builtin=true：只能复制后再改，不能直接编辑或删除，避免用户把预设改坏。
-- on conflict do nothing：重复执行不会覆盖同名主题。

insert into theme_preset
    (theme_key, name, description, base_theme_key, preview_image_url, definition_json, builtin, enabled, version)
values
    ('preset-minimal', '极简', '大留白、无边框、去装饰，让内容自己说话。', 'travel-classic', null,
     '{"colors":{"background":"#FFFFFF","surface":"#FFFFFF","surfaceSoft":"#F4F4F5","primary":"#18181B","primarySoft":"#52525B","secondary":"#71717A","accent":"#18181B","accentHover":"#3F3F46","sand":"#E4E4E7","text":"#27272A","muted":"#A1A1AA","border":"#E4E4E7","danger":"#DC2626","scheme":"light"},"typography":{"headingFamily":"sans","bodyFamily":"sans","bodySize":16,"lineHeight":1.9,"letterSpacing":0,"headingWeight":600,"paragraphSpacing":1.4,"headingStyle":"plain"},"shape":{"cardRadius":4,"imageRadius":2,"buttonRadius":4,"borderWidth":0},"layout":{"contentWidth":1080,"articleWidth":680,"sectionGap":1.4,"density":"relaxed","homeLayout":"classic","journalLayout":"single"},"card":{"style":"flat","opacity":1,"blur":0},"background":{"style":"solid","texture":"none","intensity":0},"image":{"style":"natural","shadow":"none","defaultRatio":"16:9","frame":"none","tone":"none","width":"medium","maxHeight":70},"gallery":{"layout":"grid","columns":3,"gap":6},"motion":{"level":"subtle","hover":"none","entrance":false,"scrollReveal":false},"effects":{"particles":"none","grain":false,"lightLeak":false,"vignette":false},"map":{"style":"light","routeColor":"#18181B","routeWidth":2,"markerStyle":"dot","animateRoute":false},"hero":{}}'::jsonb, true, true, 1),
    ('preset-japandi', '日系', '低饱和米白与原木色，克制的衬线标题和大行距。', 'travel-classic', null,
     '{"colors":{"background":"#FAF7F2","surface":"#FFFFFF","surfaceSoft":"#F0EBE3","primary":"#3D3A34","primarySoft":"#6B655B","secondary":"#8C8578","accent":"#A67C52","accentHover":"#8C6544","sand":"#E0D5C3","text":"#4A463F","muted":"#9A9287","border":"#E5DED2","danger":"#B5544A","scheme":"light"},"typography":{"headingFamily":"serif","bodyFamily":"sans","bodySize":16,"lineHeight":2.0,"letterSpacing":0.02,"headingWeight":500,"paragraphSpacing":1.5,"headingStyle":"plain"},"shape":{"cardRadius":2,"imageRadius":2,"buttonRadius":2,"borderWidth":1},"layout":{"contentWidth":1120,"articleWidth":700,"sectionGap":1.3,"density":"relaxed","homeLayout":"editorial","journalLayout":"single"},"card":{"style":"border","opacity":1,"blur":0},"background":{"style":"solid","texture":"paper","intensity":0.35},"image":{"style":"natural","shadow":"none","defaultRatio":"4:3","frame":"line","tone":"warm","width":"medium","maxHeight":68},"gallery":{"layout":"grid","columns":2,"gap":14},"motion":{"level":"subtle","hover":"lift","entrance":true,"scrollReveal":true},"effects":{"particles":"none","grain":false,"lightLeak":false,"vignette":false},"map":{"style":"light","routeColor":"#A67C52","routeWidth":2,"markerStyle":"ring","animateRoute":false},"hero":{}}'::jsonb, true, true, 1),
    ('preset-film', '胶片', '暗底、颗粒和漏光，照片按胶片风格成组呈现。', 'travel-classic', null,
     '{"colors":{"background":"#141416","surface":"#1E1F22","surfaceSoft":"#26272B","primary":"#F0EBE1","primarySoft":"#C9C3B8","secondary":"#8A8478","accent":"#E4A853","accentHover":"#C98F3E","sand":"#4A453C","text":"#DDD8CE","muted":"#918B80","border":"#33343A","danger":"#D0574C","scheme":"dark"},"typography":{"headingFamily":"mono","bodyFamily":"sans","bodySize":15,"lineHeight":1.85,"letterSpacing":0.06,"headingWeight":500,"paragraphSpacing":1.3,"headingStyle":"serif-caps"},"shape":{"cardRadius":2,"imageRadius":0,"buttonRadius":2,"borderWidth":1},"layout":{"contentWidth":1240,"articleWidth":760,"sectionGap":1.1,"density":"comfortable","homeLayout":"masonry","journalLayout":"immersive"},"card":{"style":"film","opacity":1,"blur":0},"background":{"style":"solid","texture":"grain","intensity":0.5},"image":{"style":"natural","shadow":"floating","defaultRatio":"3:4","frame":"film","tone":"vintage","width":"large","maxHeight":80},"gallery":{"layout":"filmstrip","columns":3,"gap":8},"motion":{"level":"standard","hover":"zoom","entrance":true,"scrollReveal":true},"effects":{"particles":"dust","grain":true,"lightLeak":true,"vignette":true},"map":{"style":"vintage","routeColor":"#E4A853","routeWidth":3,"markerStyle":"dot","animateRoute":true},"hero":{}}'::jsonb, true, true, 1),
    ('preset-scrapbook', '旅行手账', '纸张纹理、胶带和拍立得，像贴在本子上的照片。', 'travel-classic', null,
     '{"colors":{"background":"#F6EFE0","surface":"#FFFCF4","surfaceSoft":"#EFE4CE","primary":"#4A5D3F","primarySoft":"#6B7D5C","secondary":"#C4783F","accent":"#D2694A","accentHover":"#B85639","sand":"#E3CFA6","text":"#3E3A32","muted":"#8A8172","border":"#DFD0B2","danger":"#C0453B","scheme":"light"},"typography":{"headingFamily":"rounded","bodyFamily":"rounded","bodySize":16,"lineHeight":1.9,"letterSpacing":0.01,"headingWeight":700,"paragraphSpacing":1.3,"headingStyle":"bar"},"shape":{"cardRadius":10,"imageRadius":4,"buttonRadius":14,"borderWidth":1},"layout":{"contentWidth":1160,"articleWidth":720,"sectionGap":1.2,"density":"comfortable","homeLayout":"timeline","journalLayout":"scrapbook"},"card":{"style":"paper","opacity":1,"blur":0},"background":{"style":"solid","texture":"paper","intensity":0.55},"image":{"style":"paper","shadow":"soft","defaultRatio":"4:3","frame":"polaroid","tone":"warm","width":"medium","maxHeight":70},"gallery":{"layout":"mosaic","columns":3,"gap":16},"motion":{"level":"standard","hover":"tilt","entrance":true,"scrollReveal":true},"effects":{"particles":"none","grain":false,"lightLeak":false,"vignette":false},"map":{"style":"vintage","routeColor":"#D2694A","routeWidth":4,"markerStyle":"pin","animateRoute":true},"hero":{}}'::jsonb, true, true, 1),
    ('preset-magazine', '杂志', '强对比标题与不对称栅格，像翻开一本旅行特刊。', 'travel-classic', null,
     '{"colors":{"background":"#FFFFFF","surface":"#FFFFFF","surfaceSoft":"#F2F0EC","primary":"#111111","primarySoft":"#444444","secondary":"#B03A2E","accent":"#C0392B","accentHover":"#A03327","sand":"#E8E4DC","text":"#1C1C1C","muted":"#767676","border":"#DEDAD2","danger":"#C0392B","scheme":"light"},"typography":{"headingFamily":"serif","bodyFamily":"sans","bodySize":16,"lineHeight":1.75,"letterSpacing":-0.01,"headingWeight":900,"paragraphSpacing":1.2,"headingStyle":"underline"},"shape":{"cardRadius":0,"imageRadius":0,"buttonRadius":0,"borderWidth":2},"layout":{"contentWidth":1320,"articleWidth":720,"sectionGap":1.2,"density":"compact","homeLayout":"magazine","journalLayout":"wide"},"card":{"style":"border","opacity":1,"blur":0},"background":{"style":"solid","texture":"none","intensity":0},"image":{"style":"natural","shadow":"none","defaultRatio":"16:9","frame":"none","tone":"none","width":"large","maxHeight":78},"gallery":{"layout":"magazine","columns":3,"gap":10},"motion":{"level":"standard","hover":"zoom","entrance":true,"scrollReveal":false},"effects":{"particles":"none","grain":false,"lightLeak":false,"vignette":false},"map":{"style":"light","routeColor":"#C0392B","routeWidth":3,"markerStyle":"dot","animateRoute":false},"hero":{}}'::jsonb, true, true, 1),
    ('preset-midnight', '暗黑', '深色背景配冷调强调色，夜里读也不刺眼。', 'travel-classic', null,
     '{"colors":{"background":"#0F1115","surface":"#171A20","surfaceSoft":"#1F232B","primary":"#E8EAED","primarySoft":"#B4B9C2","secondary":"#7C8794","accent":"#5B9DD9","accentHover":"#4A87BF","sand":"#2A2F38","text":"#D6D9DE","muted":"#868D98","border":"#2A2F38","danger":"#E0574B","scheme":"dark"},"typography":{"headingFamily":"sans","bodyFamily":"sans","bodySize":16,"lineHeight":1.85,"letterSpacing":0,"headingWeight":600,"paragraphSpacing":1.3,"headingStyle":"plain"},"shape":{"cardRadius":10,"imageRadius":8,"buttonRadius":8,"borderWidth":1},"layout":{"contentWidth":1200,"articleWidth":740,"sectionGap":1.1,"density":"comfortable","homeLayout":"editorial","journalLayout":"single"},"card":{"style":"shadow","opacity":1,"blur":0},"background":{"style":"solid","texture":"none","intensity":0},"image":{"style":"rounded","shadow":"floating","defaultRatio":"16:9","frame":"float","tone":"none","width":"medium","maxHeight":75},"gallery":{"layout":"grid","columns":3,"gap":10},"motion":{"level":"subtle","hover":"lift","entrance":true,"scrollReveal":true},"effects":{"particles":"stars","grain":false,"lightLeak":false,"vignette":true},"map":{"style":"dark","routeColor":"#5B9DD9","routeWidth":3,"markerStyle":"ring","animateRoute":true},"hero":{}}'::jsonb, true, true, 1),
    ('preset-nature', '自然', '苔绿与树皮棕，地形纹理背景，适合山野路线。', 'travel-classic', null,
     '{"colors":{"background":"#F3F5EF","surface":"#FFFFFF","surfaceSoft":"#E6EBDF","primary":"#2F4A32","primarySoft":"#4E6B50","secondary":"#7A6A4F","accent":"#6B8E4E","accentHover":"#587A3E","sand":"#CFD9BE","text":"#333B31","muted":"#7C8677","border":"#D7DFCB","danger":"#B5544A","scheme":"light","gradientFrom":"#F3F5EF","gradientTo":"#E2EAD9"},"typography":{"headingFamily":"serif","bodyFamily":"sans","bodySize":16,"lineHeight":1.9,"letterSpacing":0.01,"headingWeight":700,"paragraphSpacing":1.35,"headingStyle":"bar"},"shape":{"cardRadius":14,"imageRadius":10,"buttonRadius":20,"borderWidth":1},"layout":{"contentWidth":1200,"articleWidth":740,"sectionGap":1.2,"density":"comfortable","homeLayout":"editorial","journalLayout":"single"},"card":{"style":"border","opacity":1,"blur":0},"background":{"style":"gradient","texture":"topo","intensity":0.3},"image":{"style":"rounded","shadow":"soft","defaultRatio":"4:3","frame":"none","tone":"none","width":"medium","maxHeight":72},"gallery":{"layout":"masonry","columns":3,"gap":12},"motion":{"level":"standard","hover":"lift","entrance":true,"scrollReveal":true},"effects":{"particles":"leaves","grain":false,"lightLeak":false,"vignette":false},"map":{"style":"terrain","routeColor":"#6B8E4E","routeWidth":4,"markerStyle":"pin","animateRoute":true},"hero":{}}'::jsonb, true, true, 1),
    ('preset-glass', '玻璃拟态', '半透明磨砂卡片浮在渐变背景上。', 'travel-classic', null,
     '{"colors":{"background":"#E8EDF5","surface":"#FFFFFF","surfaceSoft":"#DDE5F0","primary":"#1E293B","primarySoft":"#475569","secondary":"#7C3AED","accent":"#6366F1","accentHover":"#4F46E5","sand":"#C7D2E4","text":"#25324A","muted":"#7A8699","border":"#CBD5E1","danger":"#E11D48","scheme":"light","gradientFrom":"#E8EDF5","gradientTo":"#D6C9F0"},"typography":{"headingFamily":"rounded","bodyFamily":"sans","bodySize":16,"lineHeight":1.8,"letterSpacing":0,"headingWeight":600,"paragraphSpacing":1.25,"headingStyle":"plain"},"shape":{"cardRadius":20,"imageRadius":16,"buttonRadius":32,"borderWidth":1},"layout":{"contentWidth":1200,"articleWidth":740,"sectionGap":1.15,"density":"comfortable","homeLayout":"bento","journalLayout":"single"},"card":{"style":"glass","opacity":0.62,"blur":18},"background":{"style":"gradient","texture":"none","intensity":0.2},"image":{"style":"rounded","shadow":"floating","defaultRatio":"16:9","frame":"float","tone":"none","width":"medium","maxHeight":74},"gallery":{"layout":"grid","columns":3,"gap":14},"motion":{"level":"standard","hover":"lift","entrance":true,"scrollReveal":true},"effects":{"particles":"none","grain":false,"lightLeak":false,"vignette":false},"map":{"style":"light","routeColor":"#6366F1","routeWidth":3,"markerStyle":"ring","animateRoute":true},"hero":{}}'::jsonb, true, true, 1),
    ('preset-retro', '复古', '奶油底、砖红与芥黄，粗边框和方角。', 'travel-classic', null,
     '{"colors":{"background":"#F5EDDE","surface":"#FFF8EA","surfaceSoft":"#EADFC8","primary":"#5C3A21","primarySoft":"#7D5636","secondary":"#D98324","accent":"#B23A2F","accentHover":"#962E25","sand":"#DEC69A","text":"#43301F","muted":"#8B7355","border":"#C9B189","danger":"#A32E24","scheme":"light"},"typography":{"headingFamily":"serif","bodyFamily":"serif","bodySize":17,"lineHeight":1.8,"letterSpacing":0.02,"headingWeight":800,"paragraphSpacing":1.25,"headingStyle":"serif-caps"},"shape":{"cardRadius":0,"imageRadius":0,"buttonRadius":0,"borderWidth":3},"layout":{"contentWidth":1120,"articleWidth":700,"sectionGap":1.1,"density":"compact","homeLayout":"classic","journalLayout":"single"},"card":{"style":"paper","opacity":1,"blur":0},"background":{"style":"solid","texture":"dots","intensity":0.28},"image":{"style":"paper","shadow":"soft","defaultRatio":"4:3","frame":"postcard","tone":"vintage","width":"medium","maxHeight":70},"gallery":{"layout":"grid","columns":2,"gap":12},"motion":{"level":"subtle","hover":"tilt","entrance":true,"scrollReveal":false},"effects":{"particles":"none","grain":true,"lightLeak":false,"vignette":false},"map":{"style":"vintage","routeColor":"#B23A2F","routeWidth":4,"markerStyle":"dot","animateRoute":false},"hero":{}}'::jsonb, true, true, 1)
on conflict (theme_key) do nothing;
