-- 日记标签与前台全文检索。
--
-- 现状：日记只能按「旅行 / 城市 / 日期」三个维度找，前台没有任何搜索入口。
-- 写到几十篇之后「我那篇讲温泉的在哪」就只能靠翻。

-- ---------------------------------------------------------------- 标签
create table journal_tag (
    id bigint generated by default as identity primary key,
    name varchar(40) not null,
    slug varchar(60) not null unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

comment on table journal_tag is '日记标签';
comment on column journal_tag.name is '标签展示名，如「温泉」';
comment on column journal_tag.slug is '标签的 URL 标识，小写字母数字短横线';

-- 关联表。删日记时连带删关联，删标签时同理，两边都不留悬空行。
create table journal_tag_relation (
    id bigint generated by default as identity primary key,
    journal_entry_id bigint not null references journal_entry(id) on delete cascade,
    journal_tag_id bigint not null references journal_tag(id) on delete cascade,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_journal_tag_relation unique (journal_entry_id, journal_tag_id)
);

comment on table journal_tag_relation is '日记与标签的多对多关联';

create index idx_journal_tag_relation_tag on journal_tag_relation(journal_tag_id);

-- ---------------------------------------------------------------- 全文检索
--
-- 用 PostgreSQL 自带的全文检索，不引 Elasticsearch（开发规范里也明确排除了）。
--
-- 中文分词是个坎：默认的 simple 配置按空白和标点切词，一整句中文会变成一个词，
-- 搜「温泉」匹配不到「泡了温泉」。所以这里不用 to_tsvector 的分词结果做主力，
-- 而是：
--   1. 生成列存归一化后的纯文本，供 ILIKE 子串匹配用——中文场景下子串匹配反而最准；
--   2. 配 pg_trgm 的 GIN 索引，让 ILIKE '%关键词%' 也能走索引，不必全表扫。
create extension if not exists pg_trgm;

alter table journal_entry
    add column search_text text
    generated always as (
        coalesce(title, '') || ' ' ||
        coalesce(excerpt, '') || ' ' ||
        coalesce(content_markdown, '')
    ) stored;

comment on column journal_entry.search_text is '标题+摘要+正文拼接的检索文本，由数据库自动维护，勿手工写入';

-- gin_trgm_ops 让 ILIKE '%x%' 能走索引。只对已发布日记建部分索引：
-- 前台搜索永远只查已发布内容，草稿不该进索引也不该被搜到。
create index idx_journal_search_trgm
    on journal_entry using gin (search_text gin_trgm_ops)
    where status = 'PUBLISHED';
